name: Maven Build and Package

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Checkout common module
      uses: actions/checkout@v4
      with:
        repository: HarryJLS/Spring-common  # 替换为你的公共模块仓库
        path: Spring-common
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Install common module
      run: |
        cd Spring-common
        mvn clean install -DskipTests
        cd ..
        
    - name: Install dependencies and compile
      run: mvn clean compile
        
    - name: Run tests
      run: mvn test
      
    - name: Build and package
      run: mvn clean package -DskipTests
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifacts
        path: |
          */target/*.jar
          !*/target/*-sources.jar
          !*/target/*-javadoc.jar
        retention-days: 30